title: Reset Vector
description: "A blog about software, electronics, and other harebrained schemes"
show_downloads: false
domain: "charlesetd.github.io"
url: "https://charlesetd.github.io"
github_username:  charlesetd
theme: jekyll-theme-slate
plugins:
- jekyll-feed
